install.packages("ggplot2")
library(ggplot2)
sal = read.csv("<Path>/Salaries.csv", header = TRUE)
sortedSalary = sort(sal$Salary)
salSD = sd(sortedSalary)
salMean= mean(sortedSalary)
dnorm(sortedSalary,salMean,salSD)
plot(sortedSalary, dnorm(sortedSalary,salMean,salSD), type = "l")
Norms = dnorm(sortedSalary,salMean,salSD)
Postion = as.factor(sal$Position)
dataFrames <- data.frame("Salary" = sortedSalary, "Distribution" = Norms, "Position" = Postion)
ggplot(dataFrames, aes(x = Salary, y = Distribution, color=Position)) + geom_point()