sal  = read.csv("//<Path>//")
sortedSalary = sort(sal$Salary)
plot(sal$Salary,sal$Yrs.since.phd)
regressionModel = lm(sal$Yrs.since.phd ~ sal$Salary)
abline(regressionModel)
qqnorm(sortedSalary)
qqline(sortedSalary)